### ISSUE TITLE
Cuda 12.8

### ISSUE THREAD

**Issue by infernosalex** [cr-marcstevens/hashclash#53]
I followed the instructions from this issue https://github.com/cr-marcstevens/hashclash/issues/51 but I cannot install it with CUDA

```c
/usr/include/x86_64-linux-gnu/bits/mathcalls.h(79): error: exception specification is incompatible with that of previous function "cospi" (declared at line 2601 of /usr/local/cuda-12.8/include/crt/math_functions.h)
   extern double cospi (double __x) noexcept (true); extern double __cospi (double __x) noexcept (true);
                                    ^

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: exception specification is incompatible with that of previous function "sinpi" (declared at line 2556 of /usr/local/cuda-12.8/include/crt/math_functions.h)
   extern double sinpi (double __x) noexcept (true); extern double __sinpi (double __x) noexcept (true);
                                    ^

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(79): error: exception specification is incompatible with that of previous function "cospif" (declared at line 2623 of /usr/local/cuda-12.8/include/crt/math_functions.h)
   extern float cospif (float __x) noexcept (true); extern float __cospif (float __x) noexcept (true);
                                   ^

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: exception specification is incompatible with that of previous function "sinpif" (declared at line 2579 of /usr/local/cuda-12.8/include/crt/math_functions.h)
   extern float sinpif (float __x) noexcept (true); extern float __sinpif (float __x) noexcept (true);
                                   ^

4 errors detected in the compilation of "src/md5birthdaysearch/cuda_md5.cu".
# --error 0x2 --
make[1]: *** [Makefile:1757: src/md5birthdaysearch/cuda_md5.o] Error 2
make[1]: Leaving directory '/home/infernosalex/tools/hashclash'
make: *** [Makefile:735: all] Error 2
```

**Comment by infernosalex** [comment]
I tried to use CUDA 12.6 and still doesn't work

**Comment by cr-marcstevens** [comment]
This looks like an incompatibility between OS compiler headers and the CUDA SDK.
You should look at the OS & compiler compatibility of the CUDA SDK versions and see which is the correct fit.

**Comment by infernosalex** [comment]
> This looks like an incompatibility between OS compiler headers and the CUDA SDK. You should look at the OS & compiler compatibility of the CUDA SDK versions and see which is the correct fit.

I saw that, I used Ubuntu 25.04 and Cuda works with 24.04 and I don't know how to fix, I can run in a Docker or something ?

**Comment by cr-marcstevens** [comment]
To run with CUDA in a VM or Docker I have no experience.
I think it's best to look for advice/guides elsewhere? Maybe stackoverflow or so.
